version: "3.8"

services:
  localstack:
    image: localstack/localstack
    environment:
      - SERVICES=kms
    ports:
      - 4566:4566
    volumes:
      - localstack_data:/var/lib/localstack

volumes:
  localstack_data:
