AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  GoLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./go
      Handler: main
      PackageType: Image
      Environment:
        Variables:
          env: local
          token_github:
          user_github:
          token_line_notify:
          local_kms_endpoint: http://host.docker.internal:4566
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./go
      DockerTag: latest
      DockerBuildTarget: local

