AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  GoLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./go
      Handler: main
      PackageType: Image
      Environment:
        Variables:
          env: local
          token_github_param_name: /no-commit-notify/github_token
          user_github: yuta-2001
          token_line_notify: /no-commit-notify/line_notify_token
          local_kms_endpoint: http://host.docker.internal:4566
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./go
      DockerTag: latest
      DockerBuildTarget: local

