FROM golang:1.21.0 AS builder

COPY . /workspace/go
WORKDIR /workspace/go

ENV ARCH="arm64"

ARG VERSION
RUN go mod download && \
    GOOS=linux GOARCH=${ARCH} CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o /workspace/go/main main.go

FROM public.ecr.aws/lambda/provided:al2
COPY --from=builder /workspace/go/main /main
ENTRYPOINT ["/main"]
