name: PR

on:
  pull_request:
    branches:
      - main
  
jobs:
  check-diff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Check diff
        id: diff
        run: |
          terraform_diff_count=$(git diff --name-only origin/main HEAD --relative ./terraform/ | wc -l)
          echo "diff_count=$terraform_diff_count" >> $GITHUB_ENV

    outputs:
      diff_count: ${{ env.diff_count }}

  call-deploy-terraform:
    permissions:
      id-token: write
      contents: read
    needs: check-diff
    uses: ./.github/workflows/deploy-terraform.yaml
    secrets: inherit
    with:
      command: plan
