name: PR

on:
  pull_request:
    branches:
      - main

jobs:
  check-diff:
    runs-on: ubuntu-latest
    steps:
      - run: echo "fetch_depth=$(( commits + 1 ))" >> $GITHUB_ENV
        env:
          commits: ${{ github.event.pull_request.commits }}

      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.fetch_depth }}

      - name: Fetch main branches
        run: git fetch origin main

      - name: Check diff
        id: diff
        run: |
          terraform_diff_count=$(git diff --name-only origin/main HEAD --relative ./terraform/ | wc -l)
          echo "diff_count=$terraform_diff_count" >> $GITHUB_ENV

    outputs:
      diff_count: ${{ env.diff_count }}

  call-deploy-terraform:
    permissions:
      id-token: write
      contents: read
    needs: check-diff
    if: ${{ needs.check-diff.outputs.diff_count > 0 }}
    uses: ./.github/workflows/terraform-command.yaml
    secrets: inherit
    with:
      command: plan

  hadolint-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./go/Dockerfile
          failure-threshold: warning
