name: PR

on:
  pull_request:
    branches:
      - main
  
jobs:
  check-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Check diff
        id: diff
        run: |
          terraform_diff_count=$(git diff --name-only origin/main HEAD --relative ./terraform/ | wc -l)
          echo "terraform_diff_count=$terraform_diff_count" >> $GITHUB_ENV

      - name: Call Terraform workflow
        if: ${{ env.terraform_diff_count != '0' }}
        uses: ./.github/workflows/deploy-terraform.yaml
        with:
          command: plan
        secrets:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
          AWS_ROLE_NAME: ${{ secrets.AWS_ROLE_NAME }}
          USER_GITHUB: ${{ secrets.USER_GITHUB }}
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
          TOKEN_LINE_NOTIFY: ${{ secrets.TOKEN_LINE_NOTIFY }}
