name: Deploy terraform

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'

jobs:
  call-deploy-terraform:
    name: Call terraform workflow
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/terraform-command.yaml
    with:
      command: apply -auto-approve
    secrets: inherit
