run-name: terraform workflow ${{ inputs.command }}

on:
  workflow_call:
    # inputs:
    #   command:
    #     description: 'Terraform command'
    #     required: true
    #     default: 'plan'
    #     options:
    #       - plan
    #       - apply
    #       - destroy
  workflow_dispatch:
    inputs:
      command:
        description: 'Terraform command'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply
          - destroy

env:
  TF_VERSION: 1.9.3

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ inputs.command }}

      - name: Terraform fmt
        run: terraform fmt -check

      - name: Terraform init
        run : terraform init

      - name: Terraform ${{ inputs.command }}
        run: terraform ${{ inputs.command }} \
          -auto-approve \
          -var "user_github=${{ secrets.USER_GITHUB }}" \
          -var "token_github=${{ secrets.TOKEN_GITHUB }}" \
          -var "token_line_notify=${{ secrets.TOKEN_LINE_NOTIFY }}"
