name: terraform workflow

on:
  workflow_call:
    inputs:
      command:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      command:
        description: 'Terraform command'
        required: true
        default: 'plan'
        type: choice
        options:
          - plan
          - apply -auto-approve
          - destroy

defaults:
  run:
    working-directory: terraform/enviroments/dev

env:
  TF_VERSION: 1.9.3

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform fmt
        run: terraform fmt -check

      - name: Terraform init
        run: terraform init

      - name: Terraform ${{ inputs.command }}
        run: terraform ${{ inputs.command }} -var "user_github=${{ secrets.USER_GITHUB }}"
