name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - 'go/**'

env:
  TF_VERSION: 1.9.3

jobs:
  check-diff:
    name: Check code diff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Fetch main branches
        run: git fetch origin main

      - name: Check diff
        id: diff
        run: |
          go_diff_count=$(git diff --name-only origin/main HEAD --relative ./go/ | wc -l)
          terraform_diff_count=$(git diff --name-only origin/main HEAD --relative ./terraform/ | wc -l)

          echo "go_diff_count=$go_diff_count" >> $GITHUB_ENV
          echo "terraform_diff_count=$terraform_diff_count" >> $GITHUB_ENV

    outputs:
      go_diff_count: ${{ env.go_diff_count }}
      terraform_diff_count: ${{ env.terraform_diff_count }}
  
  call-deploy-terraform:
    name: Call terraform workflow
    permissions:
      id-token: write
      contents: read
    needs: check-diff
    if: ${{ needs.check-diff.outputs.terraform_diff_count > 0 }}
    uses: ./.github/workflows/deploy-terraform.yaml
    with:
      command: apply -auto-approve
    secrets: inherit

  call-deploy-lambda:
    name: Call deploy to lambda workflow
    permissions:
      id-token: write
      contents: read
    needs: check-diff
    if: ${{ needs.check-diff.outputs.go_diff_count > 0 }}
    uses: ./.github/workflows/deploy-lambda.yaml
    secrets: inherit
