name: Deploy lambda

on:
  push:
    branches:
      - main
    paths:
      - 'go/**'

jobs:
  call-deploy-lambda:
    name: Call deploy to lambda workflow
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/lambda-deploy-command.yaml
    secrets: inherit
