name: Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - 'go/**'

env:
  TF_VERSION: 1.9.3

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Check diff
        id: diff
        run: |
          go_diff_count=$(git diff --name-only origin/main HEAD --relative ./go/ | wc -l)
          terraform_diff_count=$(git diff --name-only origin/main HEAD --relative ./terraform/ | wc -l)

          echo "go_diff_count=$go_diff_count" >> $GITHUB_ENV
          echo "terraform_diff_count=$terraform_diff_count" >> $GITHUB_ENV

      - name: Call Terraform workflow
        if: ${{ env.terraform_diff_count != '0' }}
        uses: ./.github/workflows/deploy-terraform
        with:
          command: apply

      - name: Call Lambda workflow
        if: ${{ env.go_diff_count != '0' }}
        uses: ./.github/workflows/deploy-lambda
